export interface Project {
  id: string;
  year: string;
  title: string;
  short: string;
  long: string;
  tech: string[];
  repo: string | null;
  live: string | null;
  tags: string[];
  note?: string;
}

export interface Skill {
  category: string;
  icon: string;
  description: string;
  items: string[];
}

export interface Principle {
  title: string;
  description: string;
}

export interface Highlight {
  value: string;
  label: string;
}

export interface SocialLink {
  name: string;
  url: string;
  icon: string;
}

export const personalInfo = {
  name: "Dikshita Konwar",
  title: "Portfolio",
  headline: "Dikshita Konwar",
  subheadline:
    "A warmer, more editorial portfolio direction with stronger typography, calmer contrast, and a point of view that feels human.",
  intro:
    "This version of the site is built to feel authored rather than autogenerated. It gives your work space to breathe, adds more personality to the visual system, and creates a better base for your real projects and story.",
  bio: [
    "The redesign shifts the site away from the usual neon template look and toward something more composed. The spacing is slower, the surfaces feel richer, and the presentation is focused on taste and clarity instead of visual noise.",
    "It is still easy to personalize from here. Replace the sample project slots with your real work, plug in your actual resume and links, and the overall system is already shaped to support a much more memorable portfolio.",
  ],
  location: "India",
  email: "",
  resumeUrl: "",
  avatarUrl: "/images/avatar-placeholder.svg",
  availability:
    "Open to internships, freelance opportunities, and thoughtful collaborations.",
  status:
    "Currently shaping a portfolio identity that feels personal, confident, and unmistakably yours.",
  highlights: [
    { value: "Human-first", label: "Visual language" },
    { value: "Editorial", label: "Layout rhythm" },
    { value: "Intentional", label: "Motion and detail" },
  ] satisfies Highlight[],
  focusAreas: [
    "Show the strongest project first and let it carry the narrative.",
    "Use a tighter set of colors and type styles so the work feels authored.",
    "Present process, taste, and outcomes instead of only listing features.",
  ],
  principles: [
    {
      title: "Clarity over clutter",
      description:
        "The design favors strong hierarchy, generous spacing, and a cleaner story over decorative overload.",
    },
    {
      title: "Warmth over default polish",
      description:
        "Color, type, and surface treatment are tuned to feel crafted instead of interchangeable.",
    },
    {
      title: "Momentum over filler",
      description:
        "Each section is built to support real case studies, experiments, and writing once you plug them in.",
    },
  ] satisfies Principle[],
};

export const projects: Project[] = [
  {
    id: "signature-case-study",
    year: "2026",
    title: "Signature Case Study",
    short:
      "Use this feature slot for the one project you want a recruiter or client to remember first.",
    long: "This space works best for your flagship case study. Tell the story from challenge to outcome, explain your role clearly, and show the level of judgment you bring when details matter. The layout is ready for a more complete walkthrough once you replace the sample copy with your real work.",
    tech: ["UI Design", "Frontend", "Storytelling"],
    repo: null,
    live: null,
    tags: ["featured", "case study"],
    note: "Best used for your strongest real project.",
  },
  {
    id: "process-story",
    year: "2026",
    title: "Process Story",
    short:
      "A space for showing how your thinking evolved, not just what the final screen looked like.",
    long: "Use this section for work where the process matters as much as the result. Show iterations, explain tradeoffs, and make the reasoning visible. This is where a portfolio starts to feel less like a gallery and more like evidence of how you think.",
    tech: ["Research", "Iteration", "Presentation"],
    repo: null,
    live: null,
    tags: ["process", "craft"],
    note: "Ideal for redesigns, internships, and collaborative work.",
  },
  {
    id: "playground-build",
    year: "2026",
    title: "Playground Build",
    short:
      "Keep one spot for experiments, motion studies, or something playful that shows range.",
    long: "Not every project needs to be formal. A smaller experiment can reveal curiosity, technical confidence, and taste. This slot is designed for the kind of work that makes the portfolio feel alive and recognizably yours.",
    tech: ["Motion", "Interaction", "Prototype"],
    repo: null,
    live: null,
    tags: ["experiment", "visual"],
    note: "A great place for bold ideas or a fun technical build.",
  },
];

export const skills: Skill[] = [
  {
    category: "Visual Direction",
    icon: "sparkles",
    description:
      "A stronger point of view in typography, color, spacing, and art direction.",
    items: ["Typography", "Color Systems", "Composition", "Brand Presence"],
  },
  {
    category: "Interface Craft",
    icon: "layout",
    description:
      "UI details that make a portfolio feel designed, not assembled from a starter kit.",
    items: ["Responsive Layout", "Interaction Design", "Accessibility", "UI States"],
  },
  {
    category: "Frontend",
    icon: "code",
    description:
      "A practical implementation layer for turning visual ideas into a smooth, usable site.",
    items: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
  },
  {
    category: "Presentation",
    icon: "pen",
    description:
      "Framing projects with context, outcomes, and enough storytelling to make them stick.",
    items: ["Case Studies", "Content Strategy", "Portfolio Writing", "Narrative"],
  },
  {
    category: "Workflow",
    icon: "layers",
    description:
      "Lightweight tools and systems that keep the portfolio easy to update as your work grows.",
    items: ["Figma", "Git", "Content Structure", "Component Systems"],
  },
];

export const socialLinks: SocialLink[] = [];

export const navLinks = [
  { label: "Home", href: "#home" },
  { label: "About", href: "#about" },
  { label: "Projects", href: "#projects" },
  { label: "Skills", href: "#skills" },
  { label: "Profile", href: "#profile" },
  { label: "Contact", href: "#contact" },
];
